name = "orcfax/orcfax-aiken"
version = "0.0.1"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Orcfax types and helpers for aiken"

[repository]
user = "orcfax"
project = "orcfax-aiken"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3"
source = "github"

[config]
